version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - run:
          name: "Set registry"
          command: npm config set registry ${NPM_REGISTRY}
      - run:
          name: "Set @seneca registry"
          command: npm config set @seneca:registry ${NPM_REGISTRY}
      - run:
          name: "Set npmrc"
          command: echo 'always-auth=true' >> ~/.npmrc
      - run:
          name: "Set npmrc token"
          command: echo "//${NPM_KEY_ID}/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test
