version: 2.1
orbs:
  node: circleci/node@5.0.2
  npm-config: cobli/npm-config@1.0.0
jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      - npm-config/set-registry:
          registry-prurl: ${NPM_REGISTRY}
          scope: "@seneca"
          auth-token: ${NPM_TOKEN}
      - run:
          command: yarn install
      - run:
          command: yarn test
workflows:
  build-and-test:
    jobs:
      - build-and-test
